# Generated by Django 2.2 on 2019-12-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banglanews',
            options={'verbose_name': 'Bangla Newspaper', 'verbose_name_plural': 'Bangla Newspapers'},
        ),
    ]
