# Generated by Django 2.2 on 2019-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('news_paper_name', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('news_category', models.CharField(choices=[('MR', 'Most_read'), ('BN', 'Breaking_news'), ('NA', 'National'), ('IN', 'Inter_national'), ('PL', 'Politics'), ('SP', 'Sports'), ('EN', 'Entertainment'), ('TN', 'Technology')], default='BN', max_length=2)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
