# Generated by Django 2.2 on 2019-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News paper', 'verbose_name_plural': 'News papers'},
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('MR', 'Most read'), ('BN', 'Breaking news'), ('NA', 'National'), ('IN', 'Inter national'), ('PL', 'Politics'), ('SP', 'Sports'), ('EN', 'Entertainment'), ('TN', 'Technology')], default='MR', max_length=2),
        ),
    ]
