# Generated by Django 2.2 on 2019-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20191207_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='EnglishNews',
        ),
        migrations.RemoveIndex(
            model_name='englishnews',
            name='english_new_id_91c2c7_idx',
        ),
        migrations.AddIndex(
            model_name='englishnews',
            index=models.Index(fields=['id', 'news_category', 'news_paper_name', 'publish_time'], name='english_eng_id_16bc1f_idx'),
        ),
    ]
