# Generated by Django 2.2 on 2019-12-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_auto_20191207_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishnews',
            options={'verbose_name': 'English Newspaper', 'verbose_name_plural': 'English Newspapers'},
        ),
    ]
