# Generated by Django 2.2 on 2019-12-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_auto_20191207_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishnews',
            name='news_category',
            field=models.CharField(choices=[('Most Read', 'Most Read'), ('Breaking News', 'Breaking News'), ('National', 'National'), ('Inter National', 'Inter National'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology')], default='Most Read', max_length=20),
        ),
    ]
